export enum paginationItemsActions {
    PAGE_BACK_ITEMS = "PAGE_BACK_ITEMS",
    PAGE_FORWARD_ITEMS = "PAGE_FORWARD_ITEMS",
    NEXT_AVAILABLE_ITEMS = "NEXT_AVAILABLE_ITEMS",
    PREVIOUS_AVAILABLE_ITEMS = "PREVIOUS_AVAILABLE_ITEMS",
    SET_PAGE_ITEMS = "SET_PAGE_ITEMS",
    GET_TOTAL_PAGES_ITEMS = "GET_TOTAL_PAGES_ITEMS",
    INCREASE_OFFSET_ITEMS = "INCREASE_OFFSET_ITEMS"
}
export enum inventoryPageActions {
    ADD_INVENTORY = "ADD_INVENTORY",
    GET_INVENTORY = "GET_INVENTORY",
    GET_BY_ID = "GET_BY_ID",
    GET_BY_QUERY_INVENTORY = "GET_BY_QUERY_INVENTORY",
    GET_INVENTORY_BY_CATEGORIES = "GET_INVENTORY_BY_CATEGORIES",
    GET_AVAILABLE_INVENTORY = "GET_AVAILABLE_INVENTORY",
    DELETE_INVENTORY = "DELETE_INVENTORY",
    UPDATE_INVENTORY = "UPDATE_INVENTORY",
    ADD_CATEGORY_TO_QUERY = "ADD_CATEGORY_TO_QUERY"
}
