export enum paginationItemsActions {
    PAGE_BACK_ITEMS = "PAGE_BACK_ITEMS",
    PAGE_FORWARD_ITEMS = "PAGE_FORWARD_ITEMS",
    NEXT_AVAILABLE_ITEMS = "NEXT_AVAILABLE_ITEMS",
    PREVIOUS_AVAILABLE_ITEMS = "PREVIOUS_AVAILABLE_ITEMS",
    SET_PAGE_ITEMS = "SET_PAGE_ITEMS",
    GET_TOTAL_PAGES_ITEMS = "GET_TOTAL_PAGES_ITEMS",
    INCREASE_OFFSET_ITEMS = "INCREASE_OFFSET_ITEMS"
}

export enum itemsFetchActions {
    ADD_ITEMS_FETCH = "ADD_ITEMS_FETCH",
    GET_ITEMS_FETCH = "GET_ITEMS_FETCH",
    GET_ITEMS_BY_CATEGORIES_FETCH = "GET_ITEMS_BY_CATEGORIES_FETCH",
    DELETE_ITEM_FETCH = "DELETE_ITEM_FETCH",
    UPDATE_ITEM_FETCH = "UPDATE_ITEM_FETCH",

}
export enum inventoryPageActions {
    ADD_INVENTORY = "ADD_INVENTORY",
    GET_INVENTORY = "GET_INVENTORY",
    GET_BY_ID = "GET_BY_ID",
    GET_INVENTORY_FILTERED = "GET_INVENTORY_FILTERED",
    GET_INVENTORY_BY_CATEGORIES = "GET_INVENTORY_BY_CATEGORIES",
    GET_AVAILABLE_INVENTORY = "GET_AVAILABLE_INVENTORY",
    DELETE_INVENTORY = "DELETE_INVENTORY",
    UPDATE_INVENTORY = "UPDATE_INVENTORY",
}
