export enum paginationItemsActions {
    PAGE_BACK_ITEMS = "PAGE_BACK_ITEMS",
    PAGE_FORWARD_ITEMS = "PAGE_FORWARD_ITEMS",
    NEXT_AVAILABLE_ITEMS = "NEXT_AVAILABLE_ITEMS",
    PREVIOUS_AVAILABLE_ITEMS = "PREVIOUS_AVAILABLE_ITEMS",
    SET_PAGE_ITEMS = "SET_PAGE_ITEMS",
    GET_TOTAL_PAGES_ITEMS = "GET_TOTAL_PAGES_ITEMS",
    INCREASE_OFFSET_ITEMS = "INCREASE_OFFSET_ITEMS" 
}

export enum itemsFetchActions {
    ADD_ITEMS_FETCH = "ADD_ITEMS_FETCH",
    GET_ITEMS_FETCH = "GET_ITEMS_FETCH",
    GET_ITEMS_BY_CATEGORIES_FETCH = "GET_ITEMS_BY_CATEGORIES_FETCH",
    DELETE_ITEM_FETCH = "DELETE_ITEM_FETCH",
    UPDATE_ITEM_FETCH = "UPDATE_ITEM_FETCH",

}
export enum itemsPageActions {
    ADD_ITEMS = "ADD_ITEMS",
    GET_ITEMS = "GET_ITEMS",
    GET_ITEMS_BY_CATEGORIES = "GET_ITEMS_BY_CATEGORIES",
    DELETE_ITEM = "DELETE_ITEM",
    UPDATE_ITEM = "UPDATE_ITEM",
}
